### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by itssimon** [xing/kubernetes-oom-event-generator#13]
It would be nice to package this up as a Helm chart to make it really easy to deploy.

**Comment by TomChv** [comment]
Hi !
I made a helm chart but I can't push it the repository (`permission denied`) even if I create a new branch.
Can you help me @boosty ? I'll be glad to close this issue :joy:

**Comment by jabbrwcky** [comment]
Hi @TomChv,

please fork the repo, push your changes there and open a PR so we can discuss the changes

**Comment by aslafy-z** [comment]
I was using @TomChv PR until the branch was deleted the other day. Since then, I migrated using [stakater's `application` chart](https://github.com/stakater-charts/application) - `0.0.73` version, they then deleted the ClusterRole/CRB feature. Here are my values for reference:

```yaml
applicationName: oom-event-generator
labels:
  group: com.my-group
  team: my-team
deployment:
  replicas: 1
  image:
    repository: xingse/kubernetes-oom-event-generator
    tag: v1.2.0
  env:
    - name: VERBOSE
      value: "1"
  ports:
    - containerPort: 10254
      name: metrics
      protocol: TCP
  probes:
    readinessProbe:
      httpGet:
        path: /metrics
        port: metrics
      initialDelaySeconds: 10
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /metrics
        port: metrics
      initialDelaySeconds: 10
      periodSeconds: 10
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
service:
  ports:
    - name: metrics
      port: 10254
      protocol: TCP
      targetPort: metrics
serviceMonitor:
  enabled: true
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
rbac:
  serviceAccount:
    enabled: true
    name: oom-event-generator
  clusterroles:
    - name: oom-event-generator
      rules:
        - apiGroups:
            - ""
          resources:
            - pods
            - pods/status
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - ""
          resources:
            - events
          verbs:
            - create
            - patch
            - list
            - watch
```
